<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OTPManager.Shared\OTPManager.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FlashCap" Version="1.12.0" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.11" />
    <PackageReference Include="ZXing.Net" Version="0.16.11" />
    <PackageReference Include="ZXing.Net.Bindings.Windows.Compatibility" Version="0.16.16" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\icon.png" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Version>1.1.0</Version>
    <AssemblyVersion>1.1.0.0</AssemblyVersion>
    <FileVersion>1.1.0.0</FileVersion>
    <AssemblyName>OTPManagerV2</AssemblyName>
    <Product>OTPManagerV2</Product>
    <Company>Tomas Capdevila</Company>
    <Description>Generador y gestor de códigos de verificación en dos pasos (2FA / TOTP) para Windows</Description>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
